// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 18.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.UI.Xaml.Markup.Compiler.CodeGen
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    internal partial class VisualBasicAppPass1 : VB_CodeGenerator<PageDefinition>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
  foreach(var pair in Model.XamlFileFullPathAndCheckSums) 
  {   
            this.Write("#ExternalChecksum(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.FileName));
            this.Write("\", \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ChecksumAlgorithmGuid));
            this.Write("\", \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(pair.Checksum));
            this.Write("\")\r\n");
  }   
            this.Write(@"'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(Model.CodeInfo.ClassName.Namespace)));
            this.Write("\r\n\r\n#If Not DISABLE_XAML_GENERATED_MAIN Then\r\nPublic Module Program\r\n\r\n    \' 不写线程" +
                    "模型特性：VB 编译器对编译入口点合成注入 STAThreadAttribute，默认即 STA（Roslyn SourceMethodSymbol.vb:14" +
                    "38-1456）\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Sub Main(ByVal args() As String)   \' Module 成员隐式 Shared，不写 Shared\r\n");
  WriteCommonInit(); 
            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(".Application.Start(\r\n            Sub(p)\r\n");
  if (ProjectInfo.UsingCSWinRT) { 
            this.Write(@"                Dim context As New Global.Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(
                    Global.Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread())
                Global.System.Threading.SynchronizationContext.SetSynchronizationContext(context)
");
  } 
            this.Write("                Dim _application As New Global.");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CodeInfo.ClassName.FullName));
            this.Write("()\r\n            End Sub)\r\n    End Sub\r\n\r\nEnd Module\r\n#End If\r\n\r\n#If DISABLE_XAML_" +
                    "GENERATED_MAIN Then\r\nFriend Module XamlGeneratedProgram\r\n\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Sub XamlGeneratedMain()   \' 与 Sub Main 共享同一段初始化；Start lambda 内改调 App.XamlGe" +
                    "neratedCreateApplicationInstance()\r\n");
  WriteCommonInit(); 
            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(".Application.Start(\r\n            Sub(p)\r\n");
  if (ProjectInfo.UsingCSWinRT) { 
            this.Write(@"                Dim context As New Global.Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(
                    Global.Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread())
                Global.System.Threading.SynchronizationContext.SetSynchronizationContext(context)
");
  } 
            this.Write("                Global.");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CodeInfo.ClassName.FullName));
            this.Write(".XamlGeneratedCreateApplicationInstance()\r\n            End Sub)\r\n    End Sub\r\n\r\nE" +
                    "nd Module\r\n#End If\r\n\r\n\r\n<Global.Microsoft.VisualBasic.CompilerServices.DesignerG" +
                    "enerated()>  _\r\nPartial Class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CodeInfo.ClassName.ShortName));
            this.Write("\r\n    Inherits Global.");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CodeInfo.BaseTypeName));
            this.Write("\r\n\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    Private _contentLoaded As Boolean\r\n\r\n#If DISABLE_XAML_GENERATED_MAIN Then\r\n" +
                    "    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Friend Shared Sub XamlGeneratedCreateApplicationInstance()   \' 外层：镜像 C# int" +
                    "ernal static（CSharpAppPass1.tt:81）\r\n        _XamlGeneratedCreateApplicationInsta" +
                    "nce()\r\n    End Sub\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Private Shared Partial Sub _XamlGeneratedCreateApplicationInstance()   \' 内层" +
                    "：声明，镜像 C# private static partial（:88）；实体由 PagePass2 IsApplication 分支补\r\n    End S" +
                    "ub\r\n#End If\r\n");
 if((!ProjectInfo.GenerateProviderCode) && (!ProjectInfo.EnableTypeInfoReflection))
 {
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Public Sub AddOtherProvider(otherProvider as ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.XamlMarkup)));
            this.Write(".IXamlMetadataProvider)\r\n        _AddOtherProvider(otherProvider)\r\n    End Sub\r\n " +
                    "   Private Partial Sub _AddOtherProvider(otherProvider as ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.XamlMarkup)));
            this.Write(".IXamlMetadataProvider)\r\n    End Sub\r\n\r\n");
 }
            this.Write("    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            this.Write("\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DebuggerNonUserCodeAttribute));
            this.Write("\r\n    Public Sub InitializeComponent()\r\n        If _contentLoaded Then\r\n         " +
                    "   Return\r\n        End If\r\n        _contentLoaded = true\r\n\r\n        Dim resource" +
                    "Locator As New Global.System.Uri(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetLoadComponentUri(Model.CodeInfo.PriIndexName, Model.CodeInfo.BaseApparentRelativePath)));
            this.Write("\")\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(".Application.LoadComponent(Me, resourceLocator)\r\n\r\n#If Debug AndAlso Not DISABLE_" +
                    "XAML_GENERATED_BINDING_DEBUG_OUTPUT Then\r\n        AddHandler Me.DebugSettings.Bi" +
                    "ndingFailed,\r\n            Sub(Sender As Global.System.Object, bindingFailedArgs " +
                    "As ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(@".BindingFailedEventArgs)
                Global.System.Diagnostics.Debug.WriteLine(bindingFailedArgs.Message)
            End Sub
#End If

#If Debug AndAlso Not DISABLE_XAML_GENERATED_RESOURCE_REFERENCE_DEBUG_OUTPUT Then
        AddHandler Me.DebugSettings.XamlResourceReferenceFailed,
            Sub(Sender As Global.System.Object, resourceReferenceFailedArgs As ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(@".XamlResourceReferenceFailedEventArgs)
                Global.System.Diagnostics.Debug.WriteLine(resourceReferenceFailedArgs.Message)
            End Sub
#End If

#If Debug AndAlso Not DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION Then
        AddHandler Me.UnhandledException,
            Sub(sender As Global.System.Object, unhandledExceptionArgs As ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownNamespaces.Xaml)));
            this.Write(@".UnhandledExceptionEventArgs)
                If Global.System.Diagnostics.Debugger.IsAttached Then
                    Global.System.Diagnostics.Debugger.Break()
                End If
            End Sub
#End If
    End Sub

End Class

End Namespace
");
            return this.GenerationEnvironment.ToString();
        }
     private void WriteCommonInit() 
     { 
         if (ProjectInfo.UsingCSWinRT) { 
this.Write("        Global.WinRT.ComWrappersSupport.InitializeComWrappers()\r\n");

         } 
         foreach (var change in ProjectInfo.EnabledXamlOptionalChanges) { 
this.Write("        ");

this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownTypes.XamlOptionalChanges)));

this.Write(".EnableChange(");

this.Write(this.ToStringHelper.ToStringWithCulture(int.TryParse(change, out _) ? $"CType({change}, {Globalize(KnownTypes.XamlChangeId)})" : $"{Globalize(KnownTypes.XamlChangeId)}.{change}"));

this.Write(")\r\n");

         } 
         foreach (var change in ProjectInfo.DisabledXamlOptionalChanges) { 
this.Write("        ");

this.Write(this.ToStringHelper.ToStringWithCulture(Globalize(KnownTypes.XamlOptionalChanges)));

this.Write(".DisableChange(");

this.Write(this.ToStringHelper.ToStringWithCulture(int.TryParse(change, out _) ? $"CType({change}, {Globalize(KnownTypes.XamlChangeId)})" : $"{Globalize(KnownTypes.XamlChangeId)}.{change}"));

this.Write(")\r\n");

         } 
     } 
    }
}
